version: "3.9"

services:
  mgmt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supabase-mgmt
    networks:
      - supabase-network
    volumes:
      - /home/docker/secrets/migration.env:/config/migration.env:ro
    tty: true

networks:
  supabase-network:
    external: true
